#!/usr/bin/env python3
import os
import sys
import shutil
import subprocess
from tempfile import mkstemp


def get_editor():
    # try to get the default editor via check the environment variables
    editor = os.getenv('VISUAL', os.getenv('EDITOR'))

    while not editor or not shutil.which(editor):
        # if the output is None or empty string, let user enter it manually
        # and here, use shutil.which() to check if the editor is exists
        print("The editor which we're trying to use doesn't exist.")
        editor = shutil.which(input("Enter the editor you want to use: "))
        print()
    else:
        editor = shutil.which(editor)

    return editor


# set the file's suffix if a shell argument is giving
# since some editors have code highlight which depends on the suffix
suffix = '.' + (sys.argv[1] if len(sys.argv) > 1 else 'txt')

# create the temp file
fd, fname = mkstemp(suffix='.txt', text=True)
os.close(fd)

# call the editor and let user edit the file
if sys.platform == 'linux':
    subprocess.call([get_editor(), fname])
elif sys.platform == 'win32':
    os.system(fname)
else:
    print("Sorry, your platform isn't support yet. "
          "Please run this program on Windows or Linux.")
    sys.exit(1)

with open(fname) as f:
    # print the file out
    for i in f:
        print(i.rstrip('\n'))

os.remove(fname)
